# -*- coding: utf-8 -*-
"""Contenu de départ coréen — 9 semaines jusqu'au départ pour Séoul.

Niveau visé : débutant solide en reprise, opérationnel sur place avec ses
parents. Registre **존댓말 (-요)** partout, vocabulaire réellement utile sur
place (pas de mots de manuel).

Chaque semaine : 20-25 items (vocab / phrases), 4-6 structures, 2 dialogues,
1 jeu de rôle, 1 note culturelle. Les items `vocab`, `phrase` et `structure`
génèrent **deux cartes** (KR→FR et FR→KR) ; la direction FR→KR est suspendue
tant que la première n'a pas 3 réussites. Les `dialogue` ne génèrent pas de
carte (on les lit à voix haute, on ne les récite pas de mémoire).

**Calendrier** : le programme est calé sur le lundi de la semaine du 18 août de
l'année de référence (l'année en cours, ou la suivante si l'on est déjà passé
la fin du programme). En 2025 cela donne exactement le calendrier prévu —
S1 18-24 août … S9 13-19 octobre, la veille du départ.
"""
import datetime as _dt
import json

# (type, kr, romaja, fr, exemple_kr, exemple_fr)
V = "vocab"
P = "phrase"
S = "structure"
D = "dialogue"


def _dlg(titre, lignes):
    """Dialogue : `kr` = les répliques KR, `fr` = la traduction, ligne à ligne."""
    kr = "\n".join(f"{qui} : {k}" for qui, k, _f in lignes)
    fr = "\n".join(f"{qui} : {f}" for qui, _k, f in lignes)
    return (D, kr, "", fr, titre, titre)


SEMAINES = [
    # ==================================================== SEMAINE 1
    {
        "numero": 1,
        "theme": "Réveil : politesse et survie",
        "culture": "저기요 plutôt qu'un « excusez-moi » traduit littéralement : "
                   "c'est *le* mot pour interpeller quelqu'un, serveur compris. "
                   "Et l'inclinaison de tête suffit souvent — pas besoin de "
                   "phrase complète pour remercier ou s'excuser en passant.",
        "objectifs": ["Saluer et se présenter", "Dire qu'on ne comprend pas",
                      "Demander de répéter / de ralentir",
                      "Les particules 는/은 et 에서"],
        "items": [
            (P, "안녕하세요", "annyeonghaseyo", "bonjour",
             "안녕하세요, 처음 뵙겠습니다.", "Bonjour, enchanté."),
            (P, "감사합니다", "gamsahamnida", "merci",
             "도와주셔서 감사합니다.", "Merci de votre aide."),
            (P, "죄송합니다", "joesonghamnida", "je suis désolé (formel)",
             "늦어서 죄송합니다.", "Désolé d'être en retard."),
            (P, "저기요", "jeogiyo", "excusez-moi (pour interpeller)",
             "저기요, 여기 주문할게요.", "Excusez-moi, on va commander."),
            (V, "네", "ne", "oui", "네, 맞아요.", "Oui, c'est ça."),
            (V, "아니요", "aniyo", "non", "아니요, 괜찮아요.", "Non, ça va."),
            (P, "괜찮아요", "gwaenchanayo", "ça va / ce n'est pas grave",
             "괜찮아요, 신경 쓰지 마세요.", "Ce n'est rien, ne vous en faites pas."),
            (P, "잠시만요", "jamsimanyo", "un instant",
             "잠시만요, 금방 올게요.", "Un instant, je reviens tout de suite."),
            (P, "처음 뵙겠습니다", "cheoeum boepgetseumnida",
             "enchanté (première rencontre)",
             "처음 뵙겠습니다. 밥티스트예요.", "Enchanté. Je suis Baptiste."),
            (P, "저는 밥티스트예요", "jeoneun baptiseuteu-yeyo",
             "je m'appelle Baptiste", "저는 밥티스트예요. 반갑습니다.",
             "Je m'appelle Baptiste. Ravi de vous rencontrer."),
            (P, "프랑스에서 왔어요", "peurangseu-eseo wasseoyo",
             "je viens de France", "저는 프랑스에서 왔어요.",
             "Je viens de France."),
            (P, "한국어 조금 해요", "hangugeo jogeum haeyo",
             "je parle un peu coréen", "한국어 조금 해요, 천천히요.",
             "Je parle un peu coréen, doucement."),
            (P, "천천히 말해 주세요", "cheoncheonhi malhae juseyo",
             "parlez lentement s'il vous plaît",
             "죄송해요, 천천히 말해 주세요.",
             "Désolé, parlez lentement s'il vous plaît."),
            (P, "다시 한 번 말해 주세요", "dasi han beon malhae juseyo",
             "répétez encore une fois s'il vous plaît",
             "네? 다시 한 번 말해 주세요.", "Pardon ? Répétez s'il vous plaît."),
            (P, "이해 못 했어요", "ihae mot haesseoyo", "je n'ai pas compris",
             "미안해요, 이해 못 했어요.", "Désolé, je n'ai pas compris."),
            (P, "영어 하세요?", "yeongeo haseyo?", "vous parlez anglais ?",
             "혹시 영어 하세요?", "Vous parleriez anglais, par hasard ?"),
            (P, "안녕히 계세요", "annyeonghi gyeseyo",
             "au revoir (à celui qui reste)", "감사합니다, 안녕히 계세요.",
             "Merci, au revoir."),
            (P, "안녕히 가세요", "annyeonghi gaseyo",
             "au revoir (à celui qui part)", "안녕히 가세요, 조심히 가세요.",
             "Au revoir, rentrez bien."),
            (P, "반갑습니다", "bangapseumnida", "ravi de vous rencontrer",
             "만나서 반갑습니다.", "Ravi de vous rencontrer."),
            (P, "실례합니다", "sillyehamnida", "excusez-moi (pour passer)",
             "실례합니다, 좀 지나갈게요.", "Excusez-moi, je vais passer."),
            (P, "알겠습니다", "algetseumnida", "d'accord, compris",
             "네, 알겠습니다.", "Oui, compris."),
            (P, "몰라요", "mollayo", "je ne sais pas",
             "죄송해요, 잘 몰라요.", "Désolé, je ne sais pas trop."),
            (P, "부탁드려요", "butakdeuryeoyo", "s'il vous plaît (je compte sur vous)",
             "잘 부탁드려요.", "Je compte sur vous."),
            (P, "좋아요", "joayo", "c'est bien / d'accord",
             "네, 좋아요!", "Oui, très bien !"),
            (S, "-이에요 / -예요", "-ieyo / -yeyo",
             "« c'est … » — 이에요 après consonne, 예요 après voyelle",
             "저는 학생이에요. 이건 커피예요.",
             "Je suis étudiant. Ça, c'est un café."),
            (S, "-해요", "-haeyo", "présent poli (forme -요), la forme à utiliser partout",
             "저는 한국어 공부해요.", "J'étudie le coréen."),
            (S, "~ 주세요", "~ juseyo", "« donnez-moi ~ » / « faites ~ s'il vous plaît »",
             "물 주세요. 천천히 말해 주세요.",
             "De l'eau s'il vous plaît. Parlez lentement s'il vous plaît."),
            (S, "못 + verbe", "mot + verbe", "ne pas pouvoir / ne pas arriver à",
             "매운 거 못 먹어요.", "Je ne peux pas manger épicé."),
            (S, "는 / 은", "neun / eun", "particule de thème — « quant à … »",
             "저는 프랑스 사람이에요.", "Moi, je suis français."),
            (S, "에서", "eseo", "depuis (origine) / lieu où se déroule l'action",
             "프랑스에서 왔어요. 카페에서 만나요.",
             "Je viens de France. On se retrouve au café."),
        ],
        "dialogues": [
            ("Première rencontre", [
                ("A", "안녕하세요, 처음 뵙겠습니다.", "Bonjour, enchanté."),
                ("B", "안녕하세요. 반갑습니다.", "Bonjour. Ravi de vous rencontrer."),
                ("A", "저는 밥티스트예요. 프랑스에서 왔어요.",
                 "Je m'appelle Baptiste. Je viens de France."),
                ("B", "아, 한국어 잘하시네요!", "Ah, vous parlez bien coréen !"),
                ("A", "아니요, 조금 해요. 천천히 말해 주세요.",
                 "Non, un peu seulement. Parlez lentement s'il vous plaît."),
            ]),
            ("Je n'ai pas compris", [
                ("A", "저기요, 이거 어디에 있어요?",
                 "Excusez-moi, où est-ce que ça se trouve ?"),
                ("B", "(réponse rapide en coréen)", "(réponse rapide en coréen)"),
                ("A", "죄송해요, 이해 못 했어요. 다시 한 번 말해 주세요.",
                 "Désolé, je n'ai pas compris. Répétez s'il vous plaît."),
                ("B", "네, 천천히 말할게요.", "D'accord, je vais parler lentement."),
                ("A", "감사합니다!", "Merci !"),
            ]),
        ],
        "roleplay": {
            "titre": "Se présenter à l'accueil d'un hôtel",
            "role_app": "réceptionniste",
            "scenes": [
                {"app": "안녕하세요, 어떻게 오셨어요?",
                 "app_fr": "Bonjour, que puis-je pour vous ?",
                 "choix": ["안녕하세요, 저는 밥티스트예요.",
                           "저기요, 영어 하세요?", "잠시만요."]},
                {"app": "네, 프랑스에서 오셨어요?",
                 "app_fr": "Oui, vous venez de France ?",
                 "choix": ["네, 프랑스에서 왔어요.", "아니요, 괜찮아요.",
                           "이해 못 했어요."]},
                {"app": "한국어 잘하시네요!",
                 "app_fr": "Vous parlez bien coréen !",
                 "choix": ["아니요, 조금 해요.", "감사합니다!",
                           "천천히 말해 주세요."]},
            ],
        },
        "trous": [
            ("저 ___ 밥티스트예요.", "는", "particule de thème"),
            ("프랑스___ 왔어요.", "에서", "origine"),
            ("천천히 말해 ___.", "주세요", "demande polie"),
            ("매운 거 ___ 먹어요.", "못", "impossibilité"),
        ],
    },

    # ==================================================== SEMAINE 2
    {
        "numero": 2,
        "theme": "Chiffres et compteurs",
        "culture": "L'âge, les étages et les prix ne se comptent pas dans le "
                   "même système. Personne ne s'excuse de se tromper : on se "
                   "corrige et on continue. Retiens surtout que les **heures** "
                   "se disent en natif et les **minutes** en sino — c'est "
                   "l'erreur numéro un des débutants.",
        "objectifs": ["Compter dans les deux systèmes", "Les compteurs usuels",
                      "Demander un prix et une heure",
                      "한/두/세/네 devant un compteur"],
        "items": [
            (V, "일, 이, 삼, 사, 오", "il, i, sam, sa, o",
             "1 2 3 4 5 (sino-coréen)", "오 분만 기다려 주세요.",
             "Attendez cinq minutes s'il vous plaît."),
            (V, "육, 칠, 팔, 구, 십", "yuk, chil, pal, gu, sip",
             "6 7 8 9 10 (sino-coréen)", "십 분 걸려요.", "Ça prend dix minutes."),
            (V, "백", "baek", "cent", "백 원이요.", "Cent wons."),
            (V, "천", "cheon", "mille", "삼천 원이에요.", "C'est 3 000 wons."),
            (V, "만", "man", "dix mille", "만 원이요.", "Dix mille wons."),
            (V, "하나, 둘, 셋, 넷, 다섯", "hana, dul, set, net, daseot",
             "1 2 3 4 5 (natifs)", "하나, 둘, 셋!", "Un, deux, trois !"),
            (V, "여섯, 일곱, 여덟, 아홉, 열", "yeoseot, ilgop, yeodeol, ahop, yeol",
             "6 7 8 9 10 (natifs)", "열 시에 만나요.", "On se voit à 10 h."),
            (V, "명", "myeong", "compteur : personnes", "세 명이요.",
             "Trois personnes."),
            (V, "개", "gae", "compteur : objets", "두 개 주세요.",
             "Donnez-m'en deux."),
            (V, "잔", "jan", "compteur : verres, tasses",
             "아메리카노 두 잔 주세요.", "Deux americanos s'il vous plaît."),
            (V, "병", "byeong", "compteur : bouteilles", "물 한 병 주세요.",
             "Une bouteille d'eau s'il vous plaît."),
            (V, "인분", "inbun", "portion (pour X personnes)",
             "삼겹살 이인분 주세요.", "Du samgyeopsal pour deux."),
            (V, "장", "jang", "compteur : feuilles, tickets",
             "표 두 장 주세요.", "Deux tickets s'il vous plaît."),
            (V, "시", "si", "heure (avec un nombre natif)", "세 시예요.",
             "Il est trois heures."),
            (V, "분", "bun", "minute (avec un nombre sino)", "삼십 분 걸려요.",
             "Ça prend trente minutes."),
            (V, "원", "won", "won (la monnaie)", "만 오천 원이에요.",
             "Ça fait 15 000 wons."),
            (P, "얼마예요?", "eolmayeyo?", "c'est combien ?",
             "이거 얼마예요?", "Ça coûte combien ?"),
            (P, "몇 시예요?", "myeot siyeyo?", "quelle heure est-il ?",
             "지금 몇 시예요?", "Il est quelle heure ?"),
            (P, "두 개 주세요", "du gae juseyo", "donnez-m'en deux",
             "이거 두 개 주세요.", "Donnez-moi deux de ceux-là."),
            (P, "삼만 원", "samman won", "30 000 wons", "전부 삼만 원이에요.",
             "Ça fait 30 000 wons en tout."),
            (P, "두 시 삼십 분", "du si samsip bun", "2 h 30",
             "두 시 삼십 분에 만나요.", "On se retrouve à 14 h 30."),
            (P, "몇 명이세요?", "myeot myeongiseyo?", "vous êtes combien ?",
             "몇 명이세요? — 세 명이요.", "Vous êtes combien ? — Trois."),
            (P, "몇 시까지 해요?", "myeot sikkaji haeyo?",
             "vous êtes ouverts jusqu'à quelle heure ?",
             "여기 몇 시까지 해요?", "Vous fermez à quelle heure ici ?"),
            (P, "카드로 할게요", "kadeuro halgeyo", "je paierai par carte",
             "카드로 할게요.", "Je vais payer par carte."),
            (S, "한 / 두 / 세 / 네 + compteur", "han / du / se / ne",
             "하나·둘·셋·넷 se raccourcissent DEVANT un compteur",
             "한 개, 두 명, 세 잔, 네 시.",
             "Un objet, deux personnes, trois tasses, quatre heures."),
            (S, "heures natives + minutes sino", "si + bun",
             "l'heure en natif, les minutes en sino — l'erreur n°1",
             "일곱 시 십오 분이에요.", "Il est 7 h 15."),
            (S, "몇 + compteur", "myeot", "« combien de … ? »",
             "몇 개예요? 몇 시예요?", "Combien y en a-t-il ? Quelle heure ?"),
            (S, "-까지", "-kkaji", "jusqu'à (lieu ou heure)",
             "여섯 시까지 갈게요.", "J'y serai pour 18 h."),
        ],
        "dialogues": [
            ("Au comptoir du café", [
                ("A", "안녕하세요, 몇 분이세요?", "Bonjour, vous êtes combien ?"),
                ("B", "세 명이요.", "Trois."),
                ("A", "주문하시겠어요?", "Vous souhaitez commander ?"),
                ("B", "아이스 아메리카노 두 잔이랑 물 한 병 주세요.",
                 "Deux americanos glacés et une bouteille d'eau."),
                ("A", "만 이천 원입니다.", "Ça fera 12 000 wons."),
                ("B", "카드로 할게요.", "Je paie par carte."),
            ]),
            ("Quelle heure ?", [
                ("A", "저기요, 지금 몇 시예요?",
                 "Excusez-moi, il est quelle heure ?"),
                ("B", "네 시 이십 분이에요.", "Il est 16 h 20."),
                ("A", "여기 몇 시까지 해요?", "Vous fermez à quelle heure ici ?"),
                ("B", "아홉 시까지 해요.", "Jusqu'à 21 h."),
                ("A", "감사합니다!", "Merci !"),
            ]),
        ],
        "roleplay": {
            "titre": "Commander pour trois et payer",
            "role_app": "serveur",
            "scenes": [
                {"app": "어서 오세요, 몇 분이세요?",
                 "app_fr": "Bienvenue, vous êtes combien ?",
                 "choix": ["세 명이요.", "두 개 주세요.", "얼마예요?"]},
                {"app": "주문하시겠어요?", "app_fr": "Vous commandez ?",
                 "choix": ["아메리카노 세 잔 주세요.", "몇 시예요?",
                           "안녕히 계세요."]},
                {"app": "만 오천 원입니다.", "app_fr": "Ça fait 15 000 wons.",
                 "choix": ["카드로 할게요.", "천천히 말해 주세요.", "괜찮아요."]},
            ],
        },
        "trous": [
            ("커피 두 ___ 주세요.", "잔", "compteur des tasses"),
            ("세 ___이요.", "명", "compteur des personnes"),
            ("___ 시 삼십 분이에요.", "두", "heure en natif raccourci"),
            ("여섯 시___ 해요.", "까지", "jusqu'à"),
        ],
    },

    # ==================================================== SEMAINE 3
    {
        "numero": 3,
        "theme": "Restaurant et café",
        "culture": "On appelle le serveur, on ne l'attend pas : 저기요! est "
                   "parfaitement poli. L'eau et les 반찬 (accompagnements) sont "
                   "gratuits et se resservent — il suffit de demander.",
        "objectifs": ["Entrer, commander, payer",
                      "Demander « pas épicé »", "Emporter / sur place",
                      "Les formules de table"],
        "items": [
            (P, "몇 분이세요?", "myeot buniseyo?", "vous êtes combien ? (poli)",
             "어서 오세요, 몇 분이세요?", "Bienvenue, vous êtes combien ?"),
            (P, "세 명이요", "se myeongiyo", "trois personnes",
             "세 명이요, 자리 있어요?", "Trois, vous avez de la place ?"),
            (P, "메뉴 주세요", "menyu juseyo", "la carte s'il vous plaît",
             "저기요, 메뉴 주세요.", "Excusez-moi, la carte s'il vous plaît."),
            (P, "이거 주세요", "igeo juseyo", "je prends ça",
             "이거랑 이거 주세요.", "Je prends ça et ça."),
            (P, "뭐가 맛있어요?", "mwoga masisseoyo?",
             "qu'est-ce qui est bon ?", "여기 뭐가 맛있어요?",
             "Qu'est-ce qui est bon ici ?"),
            (P, "맵지 않게 해 주세요", "maepji anke hae juseyo",
             "pas épicé s'il vous plaît (LA phrase à retenir)",
             "부모님 거는 맵지 않게 해 주세요.",
             "Pour mes parents, pas épicé s'il vous plaît."),
            (P, "물 좀 주세요", "mul jom juseyo", "de l'eau s'il vous plaît",
             "물 좀 더 주세요.", "Encore un peu d'eau s'il vous plaît."),
            (P, "계산해 주세요", "gyesanhae juseyo", "l'addition s'il vous plaît",
             "저기요, 계산해 주세요.", "Excusez-moi, l'addition."),
            (P, "카드 돼요?", "kadeu dwaeyo?", "vous prenez la carte ?",
             "카드 돼요? — 네, 됩니다.", "Vous prenez la carte ? — Oui."),
            (P, "포장해 주세요", "pojanghae juseyo", "à emporter s'il vous plaît",
             "이거 포장해 주세요.", "Ça, à emporter s'il vous plaît."),
            (P, "이인분 주세요", "i-inbun juseyo", "pour deux personnes",
             "삼겹살 이인분 주세요.", "Du samgyeopsal pour deux."),
            (P, "아이스 아메리카노 한 잔 주세요",
             "aiseu amerikano han jan juseyo", "un americano glacé",
             "아이스 아메리카노 한 잔 주세요.",
             "Un americano glacé s'il vous plaît."),
            (P, "여기서 드세요?", "yeogiseo deuseyo?",
             "c'est sur place ? (ce qu'on vous demandera)",
             "여기서 드세요? — 포장이요.", "Sur place ? — À emporter."),
            (P, "잘 먹겠습니다", "jal meokgetseumnida",
             "bon appétit (avant de manger)", "잘 먹겠습니다!",
             "Merci pour le repas ! (avant)"),
            (P, "잘 먹었습니다", "jal meogeotseumnida",
             "c'était très bon (après le repas)", "잘 먹었습니다!",
             "Merci pour le repas ! (après)"),
            (P, "저는 ~ 못 먹어요", "jeoneun ~ mot meogeoyo",
             "je ne peux pas manger ~", "저는 매운 거 못 먹어요.",
             "Je ne peux pas manger épicé."),
            (P, "반찬 좀 더 주세요", "banchan jom deo juseyo",
             "encore un peu d'accompagnements", "반찬 좀 더 주세요.",
             "Vous pouvez remettre des banchan ?"),
            (P, "맛있어요", "masisseoyo", "c'est bon", "우와, 진짜 맛있어요!",
             "Waouh, c'est vraiment bon !"),
            (P, "매워요", "maewoyo", "c'est épicé", "이거 많이 매워요?",
             "C'est très épicé, ça ?"),
            (P, "안 매운 거 있어요?", "an maeun geo isseoyo?",
             "vous avez quelque chose de non épicé ?",
             "안 매운 거 있어요?", "Vous auriez un plat pas épicé ?"),
            (V, "숟가락", "sutgarak", "cuillère", "숟가락 좀 주세요.",
             "Une cuillère s'il vous plaît."),
            (V, "젓가락", "jeotgarak", "baguettes", "젓가락 하나 더 주세요.",
             "Encore une paire de baguettes."),
            (P, "자리 있어요?", "jari isseoyo?", "vous avez de la place ?",
             "세 명인데 자리 있어요?", "On est trois, vous avez de la place ?"),
            (P, "따로 계산해 주세요", "ttaro gyesanhae juseyo",
             "on paie séparément", "따로 계산해 주세요.",
             "On règle séparément s'il vous plaît."),
            (S, "-지 않게 해 주세요", "-ji anke hae juseyo",
             "« faites-le en évitant que ce soit … »",
             "맵지 않게, 짜지 않게 해 주세요.",
             "Pas épicé, pas trop salé s'il vous plaît."),
            (S, "좀", "jom", "adoucisseur — rend toute demande polie",
             "물 좀 주세요.", "De l'eau s'il vous plaît."),
            (S, "-이랑 / -랑", "-irang / -rang", "« et » entre deux noms (oral)",
             "김치랑 밥 주세요.", "Du kimchi et du riz s'il vous plaît."),
            (S, "-돼요?", "-dwaeyo?", "« est-ce que c'est possible ? »",
             "카드 돼요? 포장 돼요?",
             "Vous prenez la carte ? C'est possible à emporter ?"),
        ],
        "dialogues": [
            ("Entrer et commander", [
                ("Serveur", "어서 오세요! 몇 분이세요?",
                 "Bienvenue ! Vous êtes combien ?"),
                ("Moi", "세 명이요.", "Trois."),
                ("Serveur", "이쪽으로 오세요.", "Par ici, je vous prie."),
                ("Moi", "저기요, 메뉴 주세요. 여기 뭐가 맛있어요?",
                 "Excusez-moi, la carte. Qu'est-ce qui est bon ici ?"),
                ("Serveur", "불고기가 제일 인기 많아요.",
                 "Le bulgogi est le plus demandé."),
                ("Moi", "그럼 불고기 이인분 주세요. 맵지 않게 해 주세요.",
                 "Alors du bulgogi pour deux. Pas épicé s'il vous plaît."),
            ]),
            ("Payer et partir", [
                ("Moi", "저기요, 계산해 주세요.", "Excusez-moi, l'addition."),
                ("Serveur", "네, 삼만 이천 원입니다.", "Oui, 32 000 wons."),
                ("Moi", "카드 돼요?", "Vous prenez la carte ?"),
                ("Serveur", "네, 됩니다.", "Oui, tout à fait."),
                ("Moi", "잘 먹었습니다. 감사합니다!",
                 "C'était très bon. Merci !"),
            ]),
        ],
        "roleplay": {
            "titre": "Entrer à trois, commander pour ses parents, payer",
            "role_app": "serveur",
            "scenes": [
                {"app": "어서 오세요! 몇 분이세요?",
                 "app_fr": "Bienvenue ! Vous êtes combien ?",
                 "choix": ["세 명이요.", "포장해 주세요.", "계산해 주세요."]},
                {"app": "주문하시겠어요?", "app_fr": "Vous commandez ?",
                 "choix": ["이거 이인분 주세요. 맵지 않게 해 주세요.",
                           "뭐가 맛있어요?", "물 좀 주세요."]},
                {"app": "음료는요?", "app_fr": "Et comme boisson ?",
                 "choix": ["물 좀 주세요.", "아이스 아메리카노 한 잔 주세요.",
                           "괜찮아요."]},
                {"app": "다 드셨어요?", "app_fr": "Vous avez terminé ?",
                 "choix": ["네, 계산해 주세요.", "잘 먹었습니다.",
                           "카드 돼요?"]},
            ],
        },
        "trous": [
            ("맵___ 않게 해 주세요.", "지", "forme négative -지 않다"),
            ("물 ___ 주세요.", "좀", "adoucisseur"),
            ("김치___ 밥 주세요.", "랑", "« et » à l'oral"),
            ("카드 ___?", "돼요", "est-ce possible ?"),
        ],
    },

    # ==================================================== SEMAINE 4
    {
        "numero": 4,
        "theme": "Transport",
        "culture": "À Séoul, l'unité d'adresse réelle est la **sortie numérotée** "
                   "du métro, pas la rue. On donne un point de repère (« en face "
                   "de la sortie 3 ») plutôt qu'un nom de voie — même les taxis "
                   "fonctionnent comme ça.",
        "objectifs": ["Prendre taxi, métro, bus", "Recharger sa T-money",
                      "Indiquer une destination", "Demander la durée"],
        "items": [
            (V, "지하철", "jihacheol", "métro", "지하철로 갈게요.",
             "Je vais y aller en métro."),
            (V, "버스", "beoseu", "bus", "버스 정류장이 어디예요?",
             "Où est l'arrêt de bus ?"),
            (V, "택시", "taeksi", "taxi", "택시 타고 가요.", "On y va en taxi."),
            (V, "공항철도", "gonghangcheoldo", "AREX (train de l'aéroport)",
             "공항철도 타면 돼요?", "On peut prendre l'AREX ?"),
            (V, "티머니", "timeoni", "carte T-money",
             "티머니 있어요.", "J'ai une T-money."),
            (P, "충전해 주세요", "chungjeonhae juseyo", "rechargez s'il vous plaît",
             "티머니 만 원 충전해 주세요.",
             "Rechargez ma T-money de 10 000 wons."),
            (P, "~까지 가 주세요", "~kkaji ga juseyo", "allez jusqu'à ~ (taxi)",
             "명동까지 가 주세요.", "À Myeongdong s'il vous plaît."),
            (P, "여기 세워 주세요", "yeogi sewo juseyo", "arrêtez-vous ici",
             "저기 앞에서 세워 주세요.", "Arrêtez-vous juste devant."),
            (P, "몇 번 출구예요?", "myeot beon chulguyeyo?",
             "c'est quelle sortie ?", "삼 번 출구예요.", "C'est la sortie 3."),
            (P, "갈아타요", "garatayo", "on change (de ligne)",
             "여기서 갈아타요.", "On change ici."),
            (P, "얼마나 걸려요?", "eolmana geollyeoyo?", "ça prend combien de temps ?",
             "여기서 얼마나 걸려요?", "Ça prend combien de temps d'ici ?"),
            (P, "이 버스 ~에 가요?", "i beoseu ~e gayo?",
             "ce bus va à ~ ?", "이 버스 서울역에 가요?",
             "Ce bus va à la gare de Séoul ?"),
            (V, "다음 역", "da-eum yeok", "la station suivante",
             "다음 역에서 내려요.", "On descend à la prochaine."),
            (P, "트렁크 좀 열어 주세요", "teureongkeu jom yeoreo juseyo",
             "ouvrez le coffre s'il vous plaît",
             "짐이 많아요, 트렁크 좀 열어 주세요.",
             "On a beaucoup de bagages, ouvrez le coffre s'il vous plaît."),
            (P, "카드 찍어요", "kadeu jjigeoyo", "on badge la carte",
             "여기에 카드 찍으세요.", "Badgez votre carte ici."),
            (P, "어디예요?", "eodiyeyo?", "c'est où ?",
             "화장실 어디예요?", "Où sont les toilettes ?"),
            (V, "표", "pyo", "ticket", "표 두 장 주세요.",
             "Deux tickets s'il vous plaît."),
            (V, "편도 / 왕복", "pyeondo / wangbok", "aller simple / aller-retour",
             "왕복으로 주세요.", "Un aller-retour s'il vous plaît."),
            (P, "여기서 내려요", "yeogiseo naeryeoyo", "je descends ici",
             "저 여기서 내려요.", "Je descends ici."),
            (P, "여기 맞아요?", "yeogi majayo?", "c'est bien ici ?",
             "여기 맞아요? — 네, 맞아요.", "C'est bien ici ? — Oui."),
            (P, "짐이 많아요", "jimi manayo", "j'ai beaucoup de bagages",
             "부모님 짐이 많아요.", "Mes parents ont beaucoup de bagages."),
            (V, "공항", "gonghang", "aéroport", "인천 공항까지 가 주세요.",
             "À l'aéroport d'Incheon s'il vous plaît."),
            (P, "천천히 가 주세요", "cheoncheonhi ga juseyo",
             "roulez doucement s'il vous plaît",
             "부모님이 계셔서요, 천천히 가 주세요.",
             "Mes parents sont là, roulez doucement s'il vous plaît."),
            (S, "-로 / -으로", "-ro / -euro", "moyen : « en / par »",
             "지하철로 가요. 카드로 할게요.",
             "On y va en métro. Je paie par carte."),
            (S, "-에 가요", "-e gayo", "aller à (destination)",
             "명동에 가요.", "Je vais à Myeongdong."),
            (S, "-에서 내려요", "-eseo naeryeoyo", "descendre à (lieu)",
             "다음 역에서 내려요.", "Je descends à la prochaine station."),
            (S, "-면 돼요?", "-myeon dwaeyo?", "« il suffit de … ? »",
             "여기서 갈아타면 돼요?", "Il suffit de changer ici ?"),
        ],
        "dialogues": [
            ("Le taxi depuis Incheon", [
                ("Moi", "안녕하세요. 트렁크 좀 열어 주세요, 짐이 많아요.",
                 "Bonjour. Ouvrez le coffre s'il vous plaît, on a beaucoup de bagages."),
                ("Chauffeur", "네, 어디로 가세요?", "Oui, vous allez où ?"),
                ("Moi", "명동까지 가 주세요. 얼마나 걸려요?",
                 "À Myeongdong s'il vous plaît. Ça prend combien de temps ?"),
                ("Chauffeur", "한 시간쯤 걸려요.", "Environ une heure."),
                ("Moi", "네, 천천히 가 주세요. 부모님이 계셔서요.",
                 "D'accord, roulez doucement s'il vous plaît, mes parents sont là."),
            ]),
            ("Dans le métro", [
                ("Moi", "저기요, 이 지하철 서울역에 가요?",
                 "Excusez-moi, ce métro va à la gare de Séoul ?"),
                ("Passant", "아니요, 여기서 갈아타세요.",
                 "Non, il faut changer ici."),
                ("Moi", "몇 번 출구예요?", "C'est quelle sortie ?"),
                ("Passant", "사 번 출구예요.", "La sortie 4."),
                ("Moi", "감사합니다!", "Merci !"),
            ]),
        ],
        "roleplay": {
            "titre": "Taxi depuis Incheon avec les valises des parents",
            "role_app": "chauffeur de taxi",
            "scenes": [
                {"app": "어디로 가세요?", "app_fr": "Vous allez où ?",
                 "choix": ["명동까지 가 주세요.", "얼마나 걸려요?",
                           "트렁크 좀 열어 주세요."]},
                {"app": "짐 있으세요?", "app_fr": "Vous avez des bagages ?",
                 "choix": ["네, 짐이 많아요. 트렁크 좀 열어 주세요.",
                           "아니요, 괜찮아요.", "카드 돼요?"]},
                {"app": "다 왔습니다.", "app_fr": "Nous sommes arrivés.",
                 "choix": ["여기 세워 주세요.", "카드 돼요?", "감사합니다!"]},
            ],
        },
        "trous": [
            ("명동___ 가 주세요.", "까지", "jusqu'à"),
            ("지하철___ 갈게요.", "로", "moyen de transport"),
            ("다음 역___ 내려요.", "에서", "lieu de l'action"),
            ("몇 ___ 출구예요?", "번", "compteur des numéros"),
        ],
    },

    # ==================================================== SEMAINE 5
    {
        "numero": 5,
        "theme": "Achats",
        "culture": "On ne marchande **pas** en boutique ni en grand magasin. "
                   "Le 좀 깎아 주세요 est réservé aux marchés type 광장시장 ou "
                   "남대문 — ailleurs, il met mal à l'aise.",
        "objectifs": ["Essayer, comparer, choisir",
                      "Demander une autre taille / couleur",
                      "Détaxe et reçu", "Dire qu'on regarde seulement"],
        "items": [
            (P, "이거 얼마예요?", "igeo eolmayeyo?", "combien coûte ceci ?",
             "이거 얼마예요?", "Ça coûte combien ?"),
            (P, "좀 깎아 주세요", "jom kkakka juseyo",
             "faites-moi un prix (marchés uniquement)",
             "두 개 사면 좀 깎아 주세요.",
             "Si j'en prends deux, faites-moi un prix."),
            (P, "입어 봐도 돼요?", "ibeo bwado dwaeyo?",
             "je peux l'essayer ? (vêtement)", "이거 입어 봐도 돼요?",
             "Je peux essayer ça ?"),
            (P, "신어 봐도 돼요?", "sineo bwado dwaeyo?",
             "je peux les essayer ? (chaussures)", "이거 신어 봐도 돼요?",
             "Je peux essayer ces chaussures ?"),
            (P, "더 큰 거 있어요?", "deo keun geo isseoyo?",
             "vous avez plus grand ?", "더 큰 거 있어요?",
             "Vous auriez une taille au-dessus ?"),
            (P, "더 작은 거 있어요?", "deo jageun geo isseoyo?",
             "vous avez plus petit ?", "더 작은 거 있어요?",
             "Vous auriez une taille en dessous ?"),
            (P, "다른 색 있어요?", "dareun saek isseoyo?",
             "vous avez une autre couleur ?", "검은색 말고 다른 색 있어요?",
             "Autre chose que du noir ?"),
            (P, "그냥 볼게요", "geunyang bolgeyo", "je regarde seulement",
             "괜찮아요, 그냥 볼게요.", "Merci, je regarde seulement."),
            (P, "이걸로 할게요", "igeollo halgeyo", "je prends celui-ci",
             "네, 이걸로 할게요.", "Bon, je prends celui-ci."),
            (P, "봉투 주세요", "bongtu juseyo", "un sac s'il vous plaît",
             "봉투 하나 주세요.", "Un sac s'il vous plaît."),
            (P, "영수증 주세요", "yeongsujeung juseyo", "le reçu s'il vous plaît",
             "영수증 주세요.", "Je peux avoir le reçu ?"),
            (V, "면세", "myeonse", "hors taxes / duty free",
             "면세 되나요?", "C'est éligible à la détaxe ?"),
            (V, "택스 리펀", "taekseu ripeon", "tax refund (détaxe)",
             "택스 리펀 돼요?", "Vous faites la détaxe ?"),
            (P, "포장해 주세요", "pojanghae juseyo", "emballez s'il vous plaît",
             "선물이에요, 포장해 주세요.",
             "C'est un cadeau, emballez-le s'il vous plaît."),
            (P, "선물이에요", "seonmurieyo", "c'est un cadeau",
             "부모님 선물이에요.", "C'est un cadeau pour mes parents."),
            (V, "사이즈", "saijeu", "taille", "사이즈가 어떻게 되세요?",
             "Vous faites quelle taille ?"),
            (P, "너무 비싸요", "neomu bissayo", "c'est trop cher",
             "좀 너무 비싸요.", "C'est un peu trop cher."),
            (V, "현금", "hyeongeum", "espèces", "현금으로 할게요.",
             "Je paie en espèces."),
            (P, "이거 뭐예요?", "igeo mwoyeyo?", "c'est quoi ça ?",
             "이거 뭐예요? 맛있어요?", "C'est quoi ? C'est bon ?"),
            (P, "어디에 있어요?", "eodie isseoyo?", "où est-ce ?",
             "화장품은 어디에 있어요?", "Où sont les cosmétiques ?"),
            (P, "하나 더 주세요", "hana deo juseyo", "un de plus",
             "하나 더 주세요.", "Encore un s'il vous plaît."),
            (P, "교환돼요?", "gyohwandwaeyo?", "c'est échangeable ?",
             "사이즈 교환돼요?", "On peut échanger la taille ?"),
            (P, "써 봐도 돼요?", "sseo bwado dwaeyo?",
             "je peux l'essayer ? (chapeau, lunettes)",
             "모자 써 봐도 돼요?", "Je peux essayer ce chapeau ?"),
            (P, "좀 생각해 볼게요", "jom saenggakhae bolgeyo",
             "je vais y réfléchir (refus poli)", "좀 생각해 볼게요, 감사합니다.",
             "Je vais réfléchir, merci."),
            (S, "-아/어 봐도 돼요?", "-a/eo bwado dwaeyo?",
             "« je peux essayer de … ? » — demande de permission",
             "입어 봐도 돼요? 먹어 봐도 돼요?",
             "Je peux l'essayer ? Je peux goûter ?"),
            (S, "더 + adjectif", "deo", "plus … (comparatif)",
             "더 큰 거, 더 싼 거.", "Plus grand, moins cher."),
            (S, "-(으)ㄹ게요", "-(eu)lgeyo",
             "intention immédiate : « je vais … » (décision prise là)",
             "이걸로 할게요. 그냥 볼게요.",
             "Je prends celui-ci. Je regarde juste."),
            (S, "-(으)ㄴ 거", "-(eu)n geo", "« le truc qui est … » — nominalise",
             "더 큰 거, 안 매운 거.",
             "Le plus grand, celui qui n'est pas épicé."),
        ],
        "dialogues": [
            ("Dans une boutique", [
                ("Vendeur", "찾으시는 거 있으세요?",
                 "Vous cherchez quelque chose en particulier ?"),
                ("Moi", "그냥 볼게요, 감사합니다.",
                 "Je regarde seulement, merci."),
                ("Moi", "저기요, 이거 입어 봐도 돼요?",
                 "Excusez-moi, je peux essayer ça ?"),
                ("Vendeur", "네, 탈의실은 저쪽이에요.",
                 "Oui, la cabine est par là."),
                ("Moi", "더 큰 거 있어요?", "Vous avez plus grand ?"),
                ("Vendeur", "네, 가져다 드릴게요.", "Oui, je vous l'apporte."),
            ]),
            ("Au marché de Gwangjang", [
                ("Moi", "이거 얼마예요?", "Ça coûte combien ?"),
                ("Marchande", "만 오천 원이요.", "15 000 wons."),
                ("Moi", "두 개 살게요. 좀 깎아 주세요.",
                 "J'en prends deux. Faites-moi un prix."),
                ("Marchande", "그럼 이만 팔천 원에 드릴게요.",
                 "Alors ce sera 28 000 wons."),
                ("Moi", "네, 이걸로 할게요. 봉투 주세요.",
                 "D'accord, je prends. Un sac s'il vous plaît."),
            ]),
        ],
        "roleplay": {
            "titre": "Acheter un cadeau et demander la détaxe",
            "role_app": "vendeur",
            "scenes": [
                {"app": "어서 오세요, 찾으시는 거 있으세요?",
                 "app_fr": "Bienvenue, vous cherchez quelque chose ?",
                 "choix": ["그냥 볼게요.", "이거 얼마예요?",
                           "다른 색 있어요?"]},
                {"app": "이건 어떠세요?", "app_fr": "Celui-ci vous plaît ?",
                 "choix": ["입어 봐도 돼요?", "더 큰 거 있어요?",
                           "너무 비싸요."]},
                {"app": "결제 도와드릴게요.", "app_fr": "Je vous encaisse.",
                 "choix": ["선물이에요, 포장해 주세요.", "택스 리펀 돼요?",
                           "영수증 주세요."]},
            ],
        },
        "trous": [
            ("이거 입어 ___ 돼요?", "봐도", "demander la permission d'essayer"),
            ("___ 큰 거 있어요?", "더", "comparatif"),
            ("이걸로 ___.", "할게요", "décision immédiate"),
            ("안 매운 ___ 있어요?", "거", "nominalisation"),
        ],
    },

    # ==================================================== SEMAINE 6
    {
        "numero": 6,
        "theme": "Demander son chemin, et gérer ses parents",
        "culture": "저희 (nous, humble) et 부모님 (parents, honorifique) sont "
                   "attendus quand on parle de ses parents à un inconnu. Ça "
                   "change immédiatement la façon dont on vous répond — on vous "
                   "prend au sérieux, et on vous aide.",
        "objectifs": ["Se repérer et demander son chemin",
                      "Parler de ses parents poliment",
                      "Adapter le rythme du groupe",
                      "Demander qu'on prenne une photo"],
        "items": [
            (P, "화장실 어디예요?", "hwajangsil eodiyeyo?",
             "où sont les toilettes ?", "저기요, 화장실 어디예요?",
             "Excusez-moi, où sont les toilettes ?"),
            (P, "여기서 멀어요?", "yeogiseo meoreoyo?", "c'est loin d'ici ?",
             "경복궁 여기서 멀어요?",
             "Le palais Gyeongbokgung est loin d'ici ?"),
            (V, "똑바로", "ttokbaro", "tout droit", "똑바로 가세요.",
             "Allez tout droit."),
            (V, "왼쪽", "oenjjok", "à gauche", "왼쪽으로 가세요.",
             "Prenez à gauche."),
            (V, "오른쪽", "oreunjjok", "à droite", "오른쪽에 있어요.",
             "C'est sur la droite."),
            (P, "길 좀 알려 주세요", "gil jom allyeo juseyo",
             "indiquez-moi le chemin s'il vous plaît",
             "죄송한데 길 좀 알려 주세요.",
             "Excusez-moi, pourriez-vous m'indiquer le chemin ?"),
            (P, "사진 좀 찍어 주시겠어요?", "sajin jom jjigeo jusigesseoyo?",
             "pourriez-vous nous prendre en photo ?",
             "저기요, 사진 좀 찍어 주시겠어요?",
             "Excusez-moi, vous pourriez nous prendre en photo ?"),
            (P, "저희 부모님이에요", "jeohui bumonimieyo", "ce sont mes parents",
             "저희 부모님이에요, 처음 오셨어요.",
             "Ce sont mes parents, ils viennent pour la première fois."),
            (P, "엘리베이터 있어요?", "ellibeiteo isseoyo?",
             "y a-t-il un ascenseur ?", "여기 엘리베이터 있어요?",
             "Il y a un ascenseur ici ?"),
            (P, "앉을 자리 있어요?", "anjeul jari isseoyo?",
             "y a-t-il de la place assise ?", "앉을 자리 있어요?",
             "Il y a où s'asseoir ?"),
            (P, "천천히 갈게요", "cheoncheonhi galgeyo",
             "on va y aller doucement", "저희는 천천히 갈게요.",
             "Nous, on va y aller doucement."),
            (P, "여기서 기다릴게요", "yeogiseo gidarilgeyo",
             "j'attendrai ici", "저는 여기서 기다릴게요.",
             "Moi j'attends ici."),
            (P, "같이 가요", "gachi gayo", "allons-y ensemble",
             "우리 같이 가요.", "On y va ensemble."),
            (P, "조심하세요", "josimhaseyo", "faites attention",
             "계단 조심하세요.", "Attention aux marches."),
            (P, "다 왔어요", "da wasseoyo", "on est arrivés",
             "거의 다 왔어요.", "On est presque arrivés."),
            (P, "여기가 어디예요?", "yeogiga eodiyeyo?", "on est où là ?",
             "죄송한데 여기가 어디예요?", "Pardon, on est où ici ?"),
            (V, "지도", "jido", "carte / plan", "지도 좀 봐도 돼요?",
             "Je peux regarder le plan ?"),
            (P, "가까워요?", "gakkawoyo?", "c'est près ?",
             "지하철역 가까워요?", "La station est près ?"),
            (P, "몇 분 걸려요?", "myeot bun geollyeoyo?",
             "ça prend combien de minutes ?", "걸어서 몇 분 걸려요?",
             "Ça prend combien de minutes à pied ?"),
            (V, "계단", "gyedan", "escalier", "계단이 많아요.",
             "Il y a beaucoup de marches."),
            (P, "쉬었다 가요", "swieotda gayo", "faisons une pause",
             "조금 쉬었다 가요.", "Faisons une petite pause."),
            (P, "괜찮으세요?", "gwaenchaneuseyo?",
             "vous allez bien ? (poli, à un aîné)",
             "어머니, 괜찮으세요?", "Maman, ça va ?"),
            (P, "도와주세요", "dowajuseyo", "aidez-moi",
             "죄송한데 좀 도와주세요.", "Pardon, pourriez-vous m'aider ?"),
            (P, "여기 앉으세요", "yeogi anjeuseyo", "asseyez-vous ici",
             "어머니, 여기 앉으세요.", "Maman, assieds-toi ici."),
            (S, "저희", "jeohui", "« nous » humble — obligatoire face à un inconnu",
             "저희 부모님이에요. 저희는 프랑스에서 왔어요.",
             "Ce sont mes parents. Nous venons de France."),
            (S, "-(으)세요", "-(eu)seyo",
             "impératif poli / honorifique sur le sujet",
             "여기 앉으세요. 조심하세요.",
             "Asseyez-vous ici. Faites attention."),
            (S, "-아/어 주시겠어요?", "-a/eo jusigesseoyo?",
             "demande très polie : « auriez-vous l'amabilité de … ? »",
             "사진 좀 찍어 주시겠어요?",
             "Pourriez-vous prendre une photo ?"),
            (S, "-(으)ㄹ 자리 / -(으)ㄹ 거", "-(eu)l jari",
             "futur/potentiel adjectival : « de quoi … »",
             "앉을 자리 있어요?", "Il y a de la place pour s'asseoir ?"),
        ],
        "dialogues": [
            ("Demander son chemin", [
                ("Moi", "저기요, 죄송한데 길 좀 알려 주세요.",
                 "Excusez-moi, pourriez-vous m'indiquer le chemin ?"),
                ("Passant", "어디 가세요?", "Vous allez où ?"),
                ("Moi", "전쟁기념관이요. 여기서 멀어요?",
                 "Au War Memorial. C'est loin d'ici ?"),
                ("Passant", "아니요, 똑바로 가다가 오른쪽이에요. 십 분쯤 걸려요.",
                 "Non, tout droit puis à droite. Environ dix minutes."),
                ("Moi", "감사합니다! 저희 부모님이 계셔서 천천히 갈게요.",
                 "Merci ! Mes parents sont avec moi, on ira doucement."),
            ]),
            ("Une photo avec les parents", [
                ("Moi", "저기요, 사진 좀 찍어 주시겠어요?",
                 "Excusez-moi, pourriez-vous nous prendre en photo ?"),
                ("Passant", "네, 그럼요!", "Oui, bien sûr !"),
                ("Moi", "저희 부모님이에요. 감사합니다.",
                 "Ce sont mes parents. Merci."),
                ("Passant", "하나, 둘, 셋!", "Un, deux, trois !"),
                ("Moi", "정말 감사합니다!", "Merci beaucoup !"),
            ]),
        ],
        "roleplay": {
            "titre": "Trouver un lieu avec ses parents, au rythme du groupe",
            "role_app": "passant",
            "scenes": [
                {"app": "네, 어디 가세요?", "app_fr": "Oui, vous allez où ?",
                 "choix": ["전쟁기념관이요. 여기서 멀어요?",
                           "화장실 어디예요?", "엘리베이터 있어요?"]},
                {"app": "저기 계단으로 올라가시면 돼요.",
                 "app_fr": "Il suffit de monter par cet escalier.",
                 "choix": ["엘리베이터 있어요? 저희 부모님이에요.",
                           "감사합니다!", "몇 분 걸려요?"]},
                {"app": "네, 저쪽에 엘리베이터 있어요.",
                 "app_fr": "Oui, il y a un ascenseur par là.",
                 "choix": ["감사합니다! 천천히 갈게요.", "다 왔어요?",
                           "조심하세요."]},
            ],
        },
        "trous": [
            ("___ 부모님이에요.", "저희", "« nous » humble"),
            ("사진 좀 찍어 ___?", "주시겠어요", "demande très polie"),
            ("여기 ___.", "앉으세요", "impératif poli"),
            ("앉___ 자리 있어요?", "을", "potentiel adjectival"),
        ],
    },

    # ==================================================== SEMAINE 7
    {
        "numero": 7,
        "theme": "Jjimjilbang et spa (THE SEOL:HA)",
        "culture": "시원해요 se dit d'un massage bien appuyé ou d'un bain "
                   "brûlant : ça veut dire « ça fait du bien », pas « c'est "
                   "frais ». Très utile pour rassurer sa mère quand elle "
                   "entend le mot pour la première fois dans un bain à 42 °C.",
        "objectifs": ["Arriver avec une réservation", "Vestiaires et casiers",
                      "Demander un massage plus doux",
                      "Dire qu'on a mal / que c'est agréable"],
        "items": [
            (V, "찜질방", "jjimjilbang", "jjimjilbang (sauna coréen)",
             "찜질방 처음이에요.", "C'est ma première fois en jjimjilbang."),
            (V, "사우나", "sauna", "sauna", "사우나 몇 시까지 해요?",
             "Le sauna est ouvert jusqu'à quelle heure ?"),
            (V, "목욕탕", "mogyoktang", "bains publics",
             "목욕탕은 지하에 있어요.", "Les bains sont au sous-sol."),
            (V, "남탕 / 여탕", "namtang / yeotang", "bains hommes / bains femmes",
             "남탕은 이쪽, 여탕은 저쪽이에요.",
             "Les bains hommes par ici, femmes par là."),
            (V, "수건", "sugeon", "serviette", "수건 두 장 주세요.",
             "Deux serviettes s'il vous plaît."),
            (V, "사물함", "samulham", "casier", "사물함 번호가 뭐예요?",
             "C'est quel numéro de casier ?"),
            (P, "예약했어요", "yeyakaesseoyo", "j'ai réservé",
             "두 명 예약했어요.", "J'ai réservé pour deux."),
            (P, "처음이에요", "cheoeumieyo", "c'est ma première fois",
             "여기 처음이에요.", "C'est ma première fois ici."),
            (P, "마사지 받고 싶어요", "masaji batgo sipeoyo",
             "je voudrais un massage", "마사지 받고 싶어요.",
             "J'aimerais prendre un massage."),
            (P, "좀 살살 해 주세요", "jom salsal hae juseyo",
             "plus doucement s'il vous plaît (LA phrase du massage)",
             "아, 좀 살살 해 주세요.", "Ah, plus doucement s'il vous plaît."),
            (P, "좀 세게 해 주세요", "jom sege hae juseyo",
             "plus fort s'il vous plaît", "좀 더 세게 해 주세요.",
             "Un peu plus fort s'il vous plaît."),
            (P, "아파요", "apayo", "ça fait mal", "거기 좀 아파요.",
             "Là, ça fait un peu mal."),
            (P, "시원해요", "siwonhaeyo",
             "ça fait du bien (massage appuyé, bain chaud)",
             "아, 시원해요!", "Ah, ça fait du bien !"),
            (P, "몇 시까지 해요?", "myeot sikkaji haeyo?",
             "c'est ouvert jusqu'à quelle heure ?", "여기 몇 시까지 해요?",
             "Vous fermez à quelle heure ?"),
            (P, "옷은 어디서 갈아입어요?", "oseun eodiseo garaibeoyo?",
             "où est-ce qu'on se change ?", "옷은 어디서 갈아입어요?",
             "Où est-ce qu'on se change ?"),
            (V, "신발", "sinbal", "chaussures", "신발은 여기에 넣으세요.",
             "Mettez vos chaussures ici."),
            (V, "열쇠", "yeolsoe", "clé", "열쇠 받으세요.", "Voici votre clé."),
            (P, "몇 번이에요?", "myeot beonieyo?", "c'est quel numéro ?",
             "제 사물함 몇 번이에요?", "C'est quel numéro, mon casier ?"),
            (P, "어떻게 해요?", "eotteoke haeyo?", "comment ça marche ?",
             "이거 어떻게 해요?", "Comment on fait pour ça ?"),
            (P, "물이 너무 뜨거워요", "muri neomu tteugeowoyo",
             "l'eau est trop chaude", "물이 너무 뜨거워요.",
             "L'eau est vraiment trop chaude."),
            (P, "쉬고 싶어요", "swigo sipeoyo", "je voudrais me reposer",
             "조금 쉬고 싶어요.", "J'aimerais me reposer un peu."),
            (P, "두 명이요", "du myeongiyo", "pour deux",
             "두 명이요, 예약했어요.", "Pour deux, j'ai réservé."),
            (P, "여기 처음 와요", "yeogi cheoeum wayo",
             "je viens ici pour la première fois",
             "저희 여기 처음 와요.", "On vient ici pour la première fois."),
            (P, "설명해 주세요", "seolmyeonghae juseyo",
             "expliquez-moi s'il vous plaît", "천천히 설명해 주세요.",
             "Expliquez-moi lentement s'il vous plaît."),
            (S, "-고 싶어요", "-go sipeoyo", "« je veux / j'aimerais … »",
             "마사지 받고 싶어요. 쉬고 싶어요.",
             "J'aimerais un massage. J'aimerais me reposer."),
            (S, "-아/어 주세요 (adverbe + 해 주세요)", "hae juseyo",
             "demander une manière : 살살 / 세게 / 천천히 해 주세요",
             "좀 살살 해 주세요.", "Faites plus doucement s'il vous plaît."),
            (S, "너무 + adjectif", "neomu", "trop … (excès)",
             "너무 뜨거워요. 너무 비싸요.",
             "C'est trop chaud. C'est trop cher."),
            (S, "어디서 + verbe", "eodiseo", "« où est-ce qu'on … ? »",
             "어디서 갈아입어요? 어디서 사요?",
             "Où est-ce qu'on se change ? Où est-ce qu'on achète ?"),
        ],
        "dialogues": [
            ("À l'accueil du spa", [
                ("Accueil", "안녕하세요, 예약하셨어요?",
                 "Bonjour, vous avez réservé ?"),
                ("Moi", "네, 두 명 예약했어요. 여기 처음 와요.",
                 "Oui, réservé pour deux. C'est notre première fois."),
                ("Accueil", "네, 신발은 여기 넣으시고 열쇠 받으세요.",
                 "Bien, mettez vos chaussures ici et prenez la clé."),
                ("Moi", "옷은 어디서 갈아입어요?",
                 "Où est-ce qu'on se change ?"),
                ("Accueil", "남탕은 이 층, 여탕은 위층이에요.",
                 "Les bains hommes à cet étage, femmes à l'étage au-dessus."),
                ("Moi", "감사합니다. 수건 두 장 주세요.",
                 "Merci. Deux serviettes s'il vous plaît."),
            ]),
            ("Pendant le massage", [
                ("Masseur", "세기 괜찮으세요?", "L'intensité vous convient ?"),
                ("Moi", "아, 좀 살살 해 주세요.",
                 "Ah, un peu plus doucement s'il vous plaît."),
                ("Masseur", "여기 아프세요?", "Ça fait mal ici ?"),
                ("Moi", "네, 거기 좀 아파요. 어깨는 시원해요.",
                 "Oui, un peu. Mais l'épaule, ça fait du bien."),
                ("Masseur", "네, 살살 할게요.", "D'accord, j'y vais doucement."),
            ]),
        ],
        "roleplay": {
            "titre": "Arriver à deux avec réservation, demander plus doux",
            "role_app": "réceptionniste du spa",
            "scenes": [
                {"app": "안녕하세요, 예약하셨어요?",
                 "app_fr": "Bonjour, vous avez réservé ?",
                 "choix": ["네, 두 명 예약했어요.", "처음이에요.",
                           "몇 시까지 해요?"]},
                {"app": "남탕과 여탕은 따로예요.",
                 "app_fr": "Les bains hommes et femmes sont séparés.",
                 "choix": ["옷은 어디서 갈아입어요?", "수건 주세요.",
                           "알겠습니다."]},
                {"app": "마사지도 하시겠어요?",
                 "app_fr": "Vous souhaitez aussi un massage ?",
                 "choix": ["네, 마사지 받고 싶어요.", "좀 살살 해 주세요.",
                           "얼마예요?"]},
            ],
        },
        "trous": [
            ("마사지 받___ 싶어요.", "고", "exprimer un désir"),
            ("좀 ___ 해 주세요.", "살살", "plus doucement"),
            ("물이 ___ 뜨거워요.", "너무", "excès"),
            ("옷은 ___ 갈아입어요?", "어디서", "où l'action se fait"),
        ],
    },

    # ==================================================== SEMAINE 8
    {
        "numero": 8,
        "theme": "Hôtel, pharmacie, urgences",
        "culture": "Les pharmacies (약국) sont partout : on décrit son symptôme "
                   "et on repart avec la dose du jour, sans ordonnance pour les "
                   "basiques. Le 파스 (patch chauffant) est vendu partout et "
                   "coûte trois fois rien — parfait pour un genou qui tire.",
        "objectifs": ["Check-in / check-out", "Décrire un symptôme",
                      "Acheter le bon médicament", "Savoir appeler à l'aide"],
        "items": [
            (P, "체크인 할게요", "chekeuin halgeyo", "je voudrais faire le check-in",
             "체크인 할게요. 예약했어요.",
             "Je voudrais faire le check-in. J'ai réservé."),
            (P, "체크아웃", "chekeuaut", "check-out",
             "체크아웃 몇 시예요?", "Le check-out est à quelle heure ?"),
            (P, "예약했어요, 이름은 ~", "yeyakaesseoyo, ireumeun ~",
             "j'ai réservé, au nom de ~",
             "예약했어요, 이름은 밥티스트예요.",
             "J'ai réservé, au nom de Baptiste."),
            (P, "짐 좀 맡길 수 있어요?", "jim jom matgil su isseoyo?",
             "je peux laisser mes bagages ?",
             "체크인 전에 짐 좀 맡길 수 있어요?",
             "Je peux laisser mes bagages avant le check-in ?"),
            (P, "와이파이 비밀번호 뭐예요?", "waipai bimilbeonho mwoyeyo?",
             "quel est le mot de passe du wifi ?",
             "와이파이 비밀번호 뭐예요?", "C'est quoi le mot de passe du wifi ?"),
            (P, "수건 좀 더 주세요", "sugeon jom deo juseyo",
             "encore des serviettes s'il vous plaît",
             "수건 두 장 좀 더 주세요.",
             "Deux serviettes de plus s'il vous plaît."),
            (V, "약국", "yakguk", "pharmacie", "근처에 약국 있어요?",
             "Il y a une pharmacie près d'ici ?"),
            (V, "병원", "byeongwon", "hôpital / cabinet médical",
             "병원에 가야 해요.", "Il faut aller chez le médecin."),
            (P, "머리가 아파요", "meoriga apayo", "j'ai mal à la tête",
             "어제부터 머리가 아파요.", "J'ai mal à la tête depuis hier."),
            (P, "배가 아파요", "baega apayo", "j'ai mal au ventre",
             "배가 너무 아파요.", "J'ai très mal au ventre."),
            (P, "다리가 아파요", "dariga apayo", "j'ai mal à la jambe",
             "많이 걸어서 다리가 아파요.",
             "J'ai mal aux jambes à force de marcher."),
            (V, "감기약", "gamgiyak", "médicament contre le rhume",
             "감기약 주세요.", "Un médicament contre le rhume s'il vous plaît."),
            (V, "소화제", "sohwaje", "digestif", "소화제 있어요?",
             "Vous avez un digestif ?"),
            (V, "두통약", "dutongyak", "médicament contre le mal de tête",
             "두통약 하나 주세요.", "Un antidouleur pour la tête."),
            (V, "파스", "paseu", "patch chauffant (parfait pour un genou)",
             "무릎에 붙일 파스 주세요.",
             "Un patch pour le genou s'il vous plaît."),
            (P, "열이 나요", "yeori nayo", "j'ai de la fièvre",
             "어제부터 열이 나요.", "J'ai de la fièvre depuis hier."),
            (P, "알레르기 있어요", "allereugi isseoyo", "j'ai une allergie",
             "땅콩 알레르기 있어요.", "Je suis allergique aux cacahuètes."),
            (P, "근처에 병원 있어요?", "geuncheoe byeongwon isseoyo?",
             "y a-t-il un hôpital à proximité ?",
             "근처에 병원 있어요?", "Il y a un hôpital dans le coin ?"),
            (V, "119", "il-il-gu", "numéro d'urgence (pompiers / ambulance)",
             "119에 전화해 주세요.", "Appelez le 119 s'il vous plaît."),
            (V, "방", "bang", "chambre", "방이 좀 추워요.",
             "Il fait un peu froid dans la chambre."),
            (P, "조식 몇 시예요?", "josik myeot siyeyo?",
             "le petit-déjeuner est à quelle heure ?", "조식 몇 시부터예요?",
             "Le petit-déjeuner est servi à partir de quelle heure ?"),
            (P, "무릎이 아파요", "mureupi apayo", "j'ai mal au genou",
             "오른쪽 무릎이 아파요.", "J'ai mal au genou droit."),
            (P, "구급차 불러 주세요", "gugeupcha bulleo juseyo",
             "appelez une ambulance", "빨리 구급차 불러 주세요!",
             "Appelez vite une ambulance !"),
            (P, "어제부터 아팠어요", "eojebuteo apasseoyo",
             "j'ai mal depuis hier", "어제부터 계속 아팠어요.",
             "J'ai mal sans arrêt depuis hier."),
            (S, "-이/가 아파요", "-i/ga apayo",
             "structure de la douleur : « la partie X a mal »",
             "머리가 아파요. 무릎이 아파요.",
             "J'ai mal à la tête. J'ai mal au genou."),
            (S, "-(으)ㄹ 수 있어요?", "-(eu)l su isseoyo?",
             "« est-ce que je peux … ? » (possibilité)",
             "짐 맡길 수 있어요?", "Je peux laisser mes bagages ?"),
            (S, "-부터", "-buteo", "à partir de (temps ou lieu)",
             "어제부터 아파요. 일곱 시부터예요.",
             "J'ai mal depuis hier. C'est à partir de 7 h."),
            (S, "-아/어야 해요", "-a/eoya haeyo", "« il faut que je … »",
             "병원에 가야 해요.", "Je dois aller chez le médecin."),
        ],
        "dialogues": [
            ("Check-in à l'hôtel", [
                ("Réception", "안녕하세요, 예약하셨어요?",
                 "Bonjour, vous avez une réservation ?"),
                ("Moi", "네, 체크인 할게요. 이름은 밥티스트예요.",
                 "Oui, je fais le check-in. Au nom de Baptiste."),
                ("Réception", "네, 확인됐습니다. 방은 이십오 층이에요.",
                 "C'est confirmé. Votre chambre est au 25e."),
                ("Moi", "와이파이 비밀번호 뭐예요? 그리고 조식 몇 시예요?",
                 "Quel est le mot de passe du wifi ? Et le petit-déjeuner ?"),
                ("Réception", "비밀번호는 방에 있고, 조식은 일곱 시부터예요.",
                 "Le mot de passe est dans la chambre, le petit-déjeuner à partir de 7 h."),
            ]),
            ("À la pharmacie", [
                ("Moi", "안녕하세요. 오른쪽 무릎이 아파요.",
                 "Bonjour. J'ai mal au genou droit."),
                ("Pharmacien", "언제부터요?", "Depuis quand ?"),
                ("Moi", "어제부터 아팠어요. 많이 걸었어요.",
                 "Depuis hier. J'ai beaucoup marché."),
                ("Pharmacien", "파스 붙이시고, 이 약 드세요.",
                 "Mettez un patch et prenez ce médicament."),
                ("Moi", "감사합니다. 얼마예요?", "Merci. Combien ça fait ?"),
            ]),
        ],
        "roleplay": {
            "titre": "Pharmacie : décrire une douleur au genou",
            "role_app": "pharmacien",
            "scenes": [
                {"app": "어디가 안 좋으세요?", "app_fr": "Qu'est-ce qui ne va pas ?",
                 "choix": ["무릎이 아파요.", "머리가 아파요.",
                           "배가 아파요."]},
                {"app": "언제부터요?", "app_fr": "Depuis quand ?",
                 "choix": ["어제부터 아팠어요.", "오늘부터요.",
                           "이해 못 했어요."]},
                {"app": "알레르기 있으세요?", "app_fr": "Vous avez des allergies ?",
                 "choix": ["아니요, 없어요.", "네, 알레르기 있어요.",
                           "잘 몰라요."]},
                {"app": "파스랑 약 드릴게요.",
                 "app_fr": "Je vous donne un patch et un médicament.",
                 "choix": ["감사합니다. 얼마예요?", "카드 돼요?",
                           "영수증 주세요."]},
            ],
        },
        "trous": [
            ("무릎___ 아파요.", "이", "particule sujet après consonne"),
            ("짐 맡길 ___ 있어요?", "수", "possibilité"),
            ("어제___ 아팠어요.", "부터", "à partir de"),
            ("병원에 가___ 해요.", "야", "obligation"),
        ],
    },

    # ==================================================== SEMAINE 9
    {
        "numero": 9,
        "theme": "Max, et révision générale",
        "culture": "Retrouver quelqu'un après longtemps se marque par "
                   "오랜만이에요 et, presque toujours, un commentaire sur "
                   "l'apparence : 하나도 안 변했네요 (« tu n'as pas changé d'un "
                   "poil ») est un compliment standard, pas une remarque en "
                   "l'air. Le rendre est attendu.",
        "objectifs": ["Retrouver un ami", "Présenter ses parents",
                      "Proposer une sortie",
                      "60 % de révision : toutes les cartes repassent"],
        "items": [
            (P, "오랜만이에요!", "oraenmanieyo!", "ça faisait longtemps !",
             "와, 진짜 오랜만이에요!", "Waouh, ça faisait vraiment longtemps !"),
            (P, "보고 싶었어요", "bogo sipeosseoyo", "tu m'as manqué",
             "진짜 보고 싶었어요.", "Tu m'as vraiment manqué."),
            (P, "잘 지냈어요?", "jal jinaesseoyo?", "tu vas bien ? (depuis le temps)",
             "그동안 잘 지냈어요?", "Tu as été bien depuis tout ce temps ?"),
            (P, "하나도 안 변했네요", "hanado an byeonhannneyo",
             "tu n'as pas changé d'un poil", "하나도 안 변했네요!",
             "Tu n'as pas changé du tout !"),
            (P, "요즘 뭐 해요?", "yojeum mwo haeyo?",
             "qu'est-ce que tu fais en ce moment ?", "요즘 뭐 해요?",
             "Tu fais quoi en ce moment ?"),
            (P, "세종대학교에서 공부했어요", "sejong daehakgyo-eseo gongbuhaesseoyo",
             "j'ai étudié à l'université Sejong",
             "저는 세종대학교에서 공부했어요.",
             "J'ai étudié à l'université Sejong."),
            (P, "소개해 드릴게요", "sogaehae deurilgeyo",
             "je vais vous présenter (humble)",
             "제 부모님 소개해 드릴게요.",
             "Je vais vous présenter mes parents."),
            (V, "전쟁기념관", "jeonjaeng ginyeomgwan", "le War Memorial of Korea",
             "전쟁기념관 가 봤어요?", "Tu as déjà été au War Memorial ?"),
            (P, "시간 내줘서 고마워요", "sigan naejwoseo gomawoyo",
             "merci d'avoir pris le temps", "시간 내줘서 고마워요.",
             "Merci d'avoir pris le temps."),
            (P, "다음에 또 만나요", "da-eume tto mannayo",
             "on se revoit la prochaine fois", "다음에 또 만나요!",
             "À la prochaine !"),
            (P, "연락할게요", "yeollakalgeyo", "je te tiens au courant",
             "도착하면 연락할게요.", "Je te fais signe en arrivant."),
            (P, "정말 좋았어요", "jeongmal joasseoyo", "c'était vraiment super",
             "오늘 정말 좋았어요.", "Aujourd'hui c'était vraiment super."),
            (P, "진짜요?", "jinjjayo?", "vraiment ?", "진짜요? 대박!",
             "Vraiment ? Génial !"),
            (P, "잘 지내요", "jal jinaeyo", "je vais bien",
             "네, 잘 지내요.", "Oui, je vais bien."),
            (P, "여기 자주 와요?", "yeogi jaju wayo?",
             "tu viens souvent ici ?", "여기 자주 와요?",
             "Tu viens souvent ici ?"),
            (P, "제 부모님이세요", "je bumonimiseyo",
             "voici mes parents (honorifique)",
             "여기 제 부모님이세요.", "Voici mes parents."),
            (P, "같이 사진 찍어요", "gachi sajin jjigeoyo",
             "prenons une photo ensemble", "우리 같이 사진 찍어요!",
             "On prend une photo ensemble !"),
            (P, "뭐 먹을래요?", "mwo meogeullaeyo?", "on mange quoi ?",
             "오늘 뭐 먹을래요?", "On mange quoi aujourd'hui ?"),
            (P, "제가 살게요", "jega salgeyo", "c'est moi qui invite",
             "오늘은 제가 살게요.", "Aujourd'hui c'est moi qui invite."),
            (P, "조심히 가세요", "josimhi gaseyo", "rentre bien",
             "조심히 가세요, 연락할게요.",
             "Rentre bien, je te fais signe."),
            (P, "또 봐요", "tto bwayo", "à bientôt", "그럼 또 봐요!",
             "Allez, à bientôt !"),
            (P, "한국 정말 좋아요", "hanguk jeongmal joayo",
             "j'aime vraiment la Corée", "한국 정말 좋아요.",
             "J'aime vraiment la Corée."),
            (P, "가 볼까요?", "ga bolkkayo?", "on y va ? / on irait bien ?",
             "전쟁기념관 가 볼까요?", "On irait bien au War Memorial ?"),
            (P, "괜찮으시면", "gwaenchaneusimyeon", "si ça vous va",
             "괜찮으시면 같이 가요.", "Si ça vous va, allons-y ensemble."),
            (S, "-았/었어요", "-at/eosseoyo", "passé poli",
             "공부했어요. 좋았어요.", "J'ai étudié. C'était bien."),
            (S, "-(으)ㄹ까요?", "-(eu)lkkayo?", "proposer : « on … ? »",
             "같이 갈까요? 뭐 먹을까요?",
             "On y va ensemble ? On mange quoi ?"),
            (S, "-아/어 드릴게요", "-a/eo deurilgeyo",
             "faire quelque chose pour quelqu'un, en humble",
             "소개해 드릴게요. 도와 드릴게요.",
             "Je vais vous présenter. Je vais vous aider."),
            (S, "-네요", "-neyo", "constat / réaction sur le vif",
             "하나도 안 변했네요! 맛있네요!",
             "Tu n'as pas changé ! C'est bon, dis donc !"),
        ],
        "dialogues": [
            ("Retrouver Max", [
                ("Moi", "막스! 오랜만이에요! 진짜 보고 싶었어요.",
                 "Max ! Ça faisait longtemps ! Tu m'as vraiment manqué."),
                ("Max", "어! 하나도 안 변했네요! 잘 지냈어요?",
                 "Oh ! Tu n'as pas changé d'un poil ! Ça va depuis le temps ?"),
                ("Moi", "네, 잘 지냈어요. 요즘 뭐 해요?",
                 "Oui, ça va. Et toi, tu fais quoi en ce moment ?"),
                ("Max", "아직 서울에서 일해요.",
                 "Je travaille toujours à Séoul."),
                ("Moi", "제 부모님 소개해 드릴게요. 여기 제 부모님이세요.",
                 "Je vais te présenter mes parents. Voici mes parents."),
            ]),
            ("Proposer le War Memorial", [
                ("Moi", "오후에 전쟁기념관 가 볼까요?",
                 "On irait bien au War Memorial cet après-midi ?"),
                ("Max", "좋아요! 부모님도 괜찮으세요?",
                 "Bonne idée ! Ça va aussi pour tes parents ?"),
                ("Moi", "네, 천천히 갈게요. 엘리베이터도 있어요.",
                 "Oui, on ira doucement. Il y a même un ascenseur."),
                ("Max", "그럼 두 시에 만나요.", "Alors on se voit à 14 h."),
                ("Moi", "네! 시간 내줘서 고마워요.",
                 "D'accord ! Merci d'avoir pris le temps."),
            ]),
        ],
        "roleplay": {
            "titre": "Retrouver Max, présenter ses parents, proposer le War Memorial",
            "role_app": "Max",
            "scenes": [
                {"app": "와, 오랜만이에요! 잘 지냈어요?",
                 "app_fr": "Waouh, ça faisait longtemps ! Ça va ?",
                 "choix": ["네, 잘 지냈어요. 보고 싶었어요.",
                           "하나도 안 변했네요!", "요즘 뭐 해요?"]},
                {"app": "이분들은?", "app_fr": "Et ces personnes ?",
                 "choix": ["제 부모님이세요. 소개해 드릴게요.",
                           "저희 부모님이에요.", "처음 뵙겠습니다."]},
                {"app": "오늘 뭐 할까요?",
                 "app_fr": "On fait quoi aujourd'hui ?",
                 "choix": ["전쟁기념관 가 볼까요?", "뭐 먹을래요?",
                           "천천히 갈게요."]},
                {"app": "그럼 저녁은 제가 살게요.",
                 "app_fr": "Alors le dîner, c'est moi qui invite.",
                 "choix": ["아니요, 제가 살게요!", "시간 내줘서 고마워요.",
                           "정말 좋았어요."]},
            ],
        },
        "trous": [
            ("세종대학교에서 공부___.", "했어요", "passé poli"),
            ("같이 갈___?", "까요", "proposition"),
            ("소개해 ___.", "드릴게요", "faire pour quelqu'un, humble"),
            ("하나도 안 변했___!", "네요", "constat sur le vif"),
        ],
    },
]

CHECKLIST_JOUR = [
    "Réviser les cartes dues",
    "5 nouveaux items de la semaine",
    "1 exercice (rotation reco → prod → trous → jeu de rôle → écoute)",
    "Lire le dialogue de la semaine à voix haute",
]

# Rotation des types d'exercice, un par jour.
ROTATION_EXOS = ["reco", "prod", "trous", "roleplay", "ecoute"]

# Les items de ces types génèrent des cartes SRS ; un dialogue se lit, il ne
# se récite pas de mémoire.
TYPES_CARTES = (V, P, S)


def date_debut_programme(aujourd_hui=None) -> _dt.date:
    """Lundi de la semaine du 18 août de l'année de référence.

    L'année de référence est l'année en cours tant qu'on n'a pas dépassé la fin
    du programme (9 semaines), sinon l'année suivante — ainsi le programme est
    toujours devant soi au premier lancement.
    """
    today = aujourd_hui or _dt.date.today()
    annee = today.year
    depart = _dt.date(annee, 8, 18)
    depart -= _dt.timedelta(days=depart.weekday())   # recule au lundi
    if today > depart + _dt.timedelta(weeks=9):
        depart = _dt.date(annee + 1, 8, 18)
        depart -= _dt.timedelta(days=depart.weekday())
    return depart


def seed(c, aujourd_hui=None):
    """Insère les 9 semaines, leurs items, cartes et exercices. Idempotent."""
    if c.execute("SELECT COUNT(*) FROM kr_semaine").fetchone()[0]:
        return
    debut = date_debut_programme(aujourd_hui)

    for sem in SEMAINES:
        d0 = debut + _dt.timedelta(weeks=sem["numero"] - 1)
        d1 = d0 + _dt.timedelta(days=6)
        cur = c.execute(
            "INSERT INTO kr_semaine(numero, theme, date_debut, date_fin, "
            "objectifs_json, note_culture) VALUES (?,?,?,?,?,?)",
            (sem["numero"], sem["theme"], d0.isoformat(), d1.isoformat(),
             json.dumps(sem["objectifs"], ensure_ascii=False),
             sem["culture"]))
        semaine_id = cur.lastrowid

        ordre = 0
        items = list(sem["items"]) + [_dlg(t, lignes)
                                      for t, lignes in sem["dialogues"]]
        for (typ, kr, romaja, fr, ex_kr, ex_fr) in items:
            ordre += 1
            icur = c.execute(
                "INSERT INTO kr_item(semaine_id, type, kr, romaja, fr, "
                "exemple_kr, exemple_fr, tags, source, ordre) "
                "VALUES (?,?,?,?,?,?,?,?,'programme',?)",
                (semaine_id, typ, kr, romaja, fr, ex_kr, ex_fr,
                 sem["theme"], ordre))
            item_id = icur.lastrowid
            if typ not in TYPES_CARTES:
                continue
            # Deux cartes : KR->FR active, FR->KR débloquée après 3 réussites.
            due = _dt.datetime.combine(d0, _dt.time(4, 0)).timestamp()
            c.execute(
                "INSERT OR IGNORE INTO kr_carte(item_id, direction, due, "
                "interval, ease, reps, lapses, suspendu) "
                "VALUES (?, 'kr_fr', ?, 0, 2.5, 0, 0, 0)", (item_id, due))
            c.execute(
                "INSERT OR IGNORE INTO kr_carte(item_id, direction, due, "
                "interval, ease, reps, lapses, suspendu) "
                "VALUES (?, 'fr_kr', ?, 0, 2.5, 0, 0, 1)", (item_id, due))

        # ---- exercices de la semaine ----
        for typ, titre, contenu, duree in (
            ("reco", f"Reconnaissance KR→FR · S{sem['numero']}",
             {"auto": True, "qcm": 4}, 5),
            ("prod", f"Production FR→KR · S{sem['numero']}",
             {"auto": True, "qcm": 4}, 5),
            ("trous", f"Texte à trous · S{sem['numero']}",
             {"phrases": [{"phrase": p, "reponse": r, "indice": i}
                          for p, r, i in sem["trous"]]}, 5),
            ("roleplay", sem["roleplay"]["titre"], sem["roleplay"], 8),
            ("ecoute", f"Écoute · S{sem['numero']}",
             {"auto": True, "qcm": 4, "lang": "ko-KR"}, 5),
        ):
            c.execute(
                "INSERT INTO kr_exercice(semaine_id, type, titre, "
                "contenu_json, duree_cible_min) VALUES (?,?,?,?,?)",
                (semaine_id, typ, titre,
                 json.dumps(contenu, ensure_ascii=False), duree))
